version: 2
jobs:
  build:
    docker:
      - image: alpine/git
    steps:
      - run:
          name: Clone
          working_directory: ~/workdir
          command: |
              git clone --depth 1 https://${GITHUB_TOKEN}@${REPO_URL} project
      - run:
          name: print README.md
          working_directory: ~/workdir/project
          command: cat README.md
      - run: echo ${GITHUB_TOKEN}, ${REPO_URL}
      - run:
          name: Build TOC
          working_directory: ~/workdir/project
          command: |
              (sed -n '1,/<!-- toc start -->/p'  README.md;
              cat README.md | (
                  grep -E "^#{${1:-1},${2:-2}} " | \
                  sed -E 's/(#+) (.+)/\1:\2:\2/g' | \
                  awk -F ":" '{ gsub(/#/,"  ",$1); gsub(/[ ]/,"-",$3); print $1 "- [" $2 "](#" tolower($3) ")" }'

              );
              sed -n '/<!-- toc end -->/,$p' README.md;) 1> aoeu;
                                              cat aoeu > README.md;
      - run:
          name: print README.md
          working_directory: ~/workdir/project
          command: cat README.md
      - deploy:
          name: Commit updated TOC
          working_directory: ~/workdir/project
          command: |
                git config credential.helper 'cache --timeout=120'
                git config user.email "danielpintjuk@gmail.com"
                git config user.name "Build Bot"
                git add README.md
                git commit --allow-empty -m "Automatically updated TOC [ci skip]"
                git push -q https://${GITHUB_TOKEN}@${REPO_URL} master